### PR TITLE
Fixes #5

### LINKED ISSUE #5: Interpolated String?
This line stuck out to me as incorrect. I don't think `"uploads"` should be interpolated in there. Perhaps that's supposed to be the configured upload path?

https://github.com/froala/wysiwyg-editor-ruby-sdk/blob/277edd662f5da9942fe7901c24b6c2acde3c99eb/lib/froala-editor-sdk/file.rb#L69

### PR DESCRIPTION
**Pull request by dheerajaccolite**

### CODE REVIEW

File: lib/froala-editor-sdk/file.rb [hunk 1]
```diff
@@ -18,13 +18,16 @@ class File
     # Default upload path.
     @default_upload_path = "public/uploads/files"
 
+    # Defult file access path
+    @default_file_access_path = "/uploads/"
```
Comment (stefanneculai) [inline lib/froala-editor-sdk/file.rb]: I'd like to move this to the `options` param rather than adding it as a completely new parameter. This would help us not to break already implementations.

Comment (akki744) [reply lib/froala-editor-sdk/file.rb]: @stefanneculai This is moved to the options param in PR for issue no. 7. Thanks.
